In [5]:
!pip install numpy

In [6]:
import numpy as np

In [5]:
np.array(object = [1,2,3], dtype=None)

array([1, 2, 3])

In [19]:
arr_1= np.array([1,2,3])
print(arr_1)
print(type(arr_1))
print('no of dimension::        ', arr_1.ndim)
print('no of elements:          ', arr_1.size)
print('index of the max no:     ', arr_1.argmax())

[1 2 3]
<class 'numpy.ndarray'>
no of dimension::         1
no of elements:           3
index of the max no:      2


In [29]:
list_1 = [1,5,6,8]
list_1

[1, 5, 6, 8]

In [30]:
list_1.extend([13,14])

In [31]:
list_1

[1, 5, 6, 8, 13, 14]

In [46]:
arr_2=np.array([4,5]) 
arr_2

array([4, 5])

In [49]:
arr_2.fill(9)

In [50]:
arr_2

array([9, 9])

In [11]:
arrey = np.array([[[1,2,5],[4,5,6],[4,5,7]]])
print(arrey)

[[[1 2 5]
  [4 5 6]
  [4 5 7]]]


In [12]:
lis_2 = [[1,4,5],[4,5,5]]
lis_2

[[1, 4, 5], [4, 5, 5]]

In [13]:
arrr = np.array(lis_2)
print(arrr)
print(type(arrr))

[[1 4 5]
 [4 5 5]]
<class 'numpy.ndarray'>


In [14]:
lil = arrr.tolist()

In [ ]:
print(type(lil))

In [ ]:
import pandas as pd

In [15]:
lil

[[1, 4, 5], [4, 5, 5]]

In [9]:
arrey = np.array([1,5,5,5])
arrey.ndim

1

In [16]:
np.median(arrey)

5.0

In [18]:
arrey

array([[[1, 2, 5],
        [4, 5, 6],
        [4, 5, 7]]])